config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations',  }
  root 'home#index'
  get '/restaurants' => 'restaurants#index'
  get '/identities/:id/edit' => 'identities#edit'

  resources :users, :identities
  resources :restaurants do
    member do
      put "like", to: "restaurants#upvote"
      put "dislike", to: "restaurants#downvote"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  acts_as_votable
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    location = params[:search]
    term = params[:term]
    sort = params[:sort]
    params = {limit: 20,
        sort: sort,
        term: term
    }
    if location.present? #&& !Yelp::Error::UnavailableForLocation
      @responses = Yelp.client.search(location, params)
      @responses.businesses.each do |response|
        if Restaurant.find_by_yelp_id(response.id)==nil
          Restaurant.create(yelp_id: response.id,
            name: response.name,
            image_url: response.image_url,
            address:response.location.display_address.to_s.gsub(/[\[\]"]/, ''),
            phone: response.phone,
            rating: ((response.rating-1)*(99/4)+1).to_i,
            latitude: response.location.coordinate.latitude,
            longitude: response.location.coordinate.longitude,
            category: response.categories.to_s.
              gsub(/[ \[\]"]/,'').
              gsub(/\b([a-z])\w+/, ' ').
              gsub(/,/, ' ')
            )
          end
        end
      end
    end

  def show

    @current_restaurant = Restaurant.find_by_yelp_id(params[:id])
    @latitude= @current_restaurant.latitude
    @longitude= @current_restaurant.longitude
    #locu api
    response = HTTParty.get(
      "https://api.locu.com/v1_0/venue/search/?" +
      "location=" + (@latitude).round(3).to_s + ", " + (@longitude).round(3).to_s +
      "&name=" + @current_restaurant.name +
      "&api_key="+ENV["LOCU_API_KEY"]
    )
    if response["objects"].empty? ==false
      @menu_id=response["objects"][response["objects"].length-1]["id"]

    #zomato api
    else
      menu_url = fetch_menu_url_from_api( @current_restaurant )
      unless menu_url == 'no match'
        doc = Nokogiri::HTML( open( menu_url ) )
        unless doc == nil
          @menu = doc.css( 'div.tmi-name' )
        end
      end
    end
  end


  def upvote
    @restaurant = Restaurant.find_by_yelp_id(params[:id])
    @restaurant.upvote_by current_user
    redirect_to request.referer + '#'+@restaurant.yelp_id
  end

  def downvote
    @restaurant = Restaurant.find_by_yelp_id(params[:id])
    @restaurant.downvote_by current_user
    redirect_to request.referer + '#'+@restaurant.yelp_id
  end


  def fetch_menu_url_from_api( db_restaurant_obj )
    fuzzy_string_match = FuzzyStringMatch::JaroWinkler.create( :native )
    best_match = 0
    menu_url = ''
    options = {
        query: {
          "q" => db_restaurant_obj.name,
          "lat" => db_restaurant_obj.latitude,
          "lon" => db_restaurant_obj.longitude
        },
        headers: { "user-key" => ENV["ZOMATO_API_KEY"] }}

    response = HTTParty.get(
      "https://developers.zomato.com/api/v2.1/search",
      options )

    zomato_restaurants = JSON.parse(response.body)['restaurants']

    zomato_restaurants.each do | restaurant |
      zomato_restaurant_name = restaurant['restaurant']['name']
      match_ratio = fuzzy_string_match.getDistance(
        db_restaurant_obj.name,
        zomato_restaurant_name )
      if match_ratio > best_match
        best_match = match_ratio
        menu_url = restaurant['restaurant']['menu_url']
      end
    end
    return best_match > 0.666 ? menu_url : 'no match'
  end



end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/index.html.erb
<% if @responses.present?%>
<div class="container">
    <% @responses.businesses.each do |place|%>
    <% @restaurant = Restaurant.find_by_yelp_id(place.id) %>
    <table id="rest_index_table">
        <tr>
            <td>
                <div id="<%=place.id%>" class="rest_index">
                    <h3 style="center"><%= link_to place.name, restaurant_path(place.id) %></h3>
                    <%= link_to href: restaurant_path(place.id) do %>
                      <%= image_tag place.image_url, :class => "img_index"%>
                    <% end %>
                </td>
                <td>
                    <h4><%= @restaurant.category%></h4>
                </td>
                <td>
                    <h5 style="font-size: 30px">
                        <strong><%= ((place.rating-1)*(99/4)+1).to_i%>%</strong>
                        <%if ((place.rating-1)*(99/4)+1).to_i >= 90 %>
                        <%= image_tag ('https://dl.dropboxusercontent.com/u/19638963/happy.png')%>
                        <%end%>
                    </h5>
                </td>
                <td>
                    <%= link_to like_restaurant_path(place.id), method: :put do %>
                    Upvote
                    <%= @restaurant.cached_votes_up %>
                    <% end %>
                    <%= link_to dislike_restaurant_path(place.id), method: :put do %>
                    Downvote
                    <%= @restaurant.cached_votes_down %>
                    <% end %>
                </div>
            </td>
        </tr>
    </table>
    <% end %>
</div>

<% else %>
<p>There are no posts containing the term(s)
    <%= params[:search] %>.</p>
<% end %>

app/views/restaurants/show.html.erb
<!DOCTYPE html>
<html>
    <head>
        <script src="//maps.google.com/maps/api/js?key=AIzaSyBZMoF3v_KL_FRtebw0rltJOYs4UoyzGwM"></script>
        <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <h1 id='rest_name_header'>
            <%= @current_restaurant.name%></h1>
        <br>
        <table id="rest_show" class="container">
            <tr>
                <td id="rest_maps">
                    <%latitude=@current_restaurant.latitude%>
                    <%longitude=@current_restaurant.longitude%>
                    <div>
                        <div id="map" style='width: 300px; height: 200px;'></div>
                    </div>
                    <script type="text/javascript">
                        handler = Gmaps.build('Google');
                        handler.buildMap({
                            provider: {},
                            internal: {
                                id: 'map'
                            }
                        }, function () {
                            markers = handler.addMarkers([
                                {
                                    lat: <%=latitude%>,
                                    lng: <%=longitude%>,
                                    picture: {
                                        url: "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
                                        width: 36,
                                        height: 36
                                    }
                                }
                            ]);
                            handler.bounds.extendWith(markers);
                            handler.fitMapToBounds();
                            handler.getMap().setZoom(15);
                        });
                    </script>
                    <h4><%= @current_restaurant.address %></h4>
                    <%@current_restaurant.phone=@current_restaurant.phone||""%>
                    <%phone = @current_restaurant.phone.gsub(/(\d{3})(\d{3})(\d{4})/, '\1-\2-\3')%>
                    <%=phone %>
                </td>
                <td class="rest_info_div">
                    <%= image_tag(@current_restaurant.image_url, class: "rest_image") %>
                    <br>
                    <br>
                    <h4><%= @current_restaurant.rating%>%</h4>
                    <%if @current_restaurant.rating.to_i >= 87 %>
                    <%= image_tag ('https://dl.dropboxusercontent.com/u/19638963/happy.png')%>
                    <%end%>
                    <h4><%= @current_restaurant.category%></h4>
                </td>
                <td id="rest_likes">
                    <%= link_to like_restaurant_path(@current_restaurant.yelp_id), method: :put do %>
                    <h4>Upvote</h4>
                    <%= @current_restaurant.cached_votes_up%>
                    <% end %>
                    <%= link_to dislike_restaurant_path(@current_restaurant.yelp_id), method: :put do %>
                    <h4>Downvote</h4>
                    <%= @current_restaurant.cached_votes_down%>
                    <% end %>
                </td>
            </tr>
        </table>
        <hr>
        <div id="menu-container">
          <div id="rest_menu">
              <%if @menu_id.present?%>
                <%src="https://widget.locu.com/menuwidget/locu.widget.developer.v2.0.js?venue-id="+@menu_id+"&widget-key="+ENV["LOCU_WIDGET_KEY"]+"&medium=web"%>
              <%elsif @menu.present?%>
                </br>
                <h2 style="text-align:center">Menu</h2>
                </br>
              <table>
                <%for i in 0..@menu.length-1%>
                <tr>
                  <td>
                    <%=@menu[i].text%>
                  </td>
                </tr>
                <%end%>
              </table>
                <%end%>
          </div>
        </div>
    </body>
</html>
<script type="text/javascript" id="-locu-widget" src=<%=src%>></script>